# -*- coding: utf-8 -*-
"""BugFix_AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Va6q_Qi40I3SREmNYAKCUDHPN9uevjbQ
"""

def divide(a, b):
    return a / b

print(divide(10, 2))

import os

# Create project folders
os.makedirs("bugfix_demo/app", exist_ok=True)
os.makedirs("bugfix_demo/tests", exist_ok=True)

print("Project folders created!")

calculator_code = '''
def calculate_average(numbers):
    return sum(numbers) / len(numbers)


def calculate_total(numbers):
    return sum(numbers)
'''

with open("bugfix_demo/app/calculator.py", "w") as f:
    f.write(calculator_code)

print("calculator.py created")

user_service_code = '''
def get_user_email(user):
    return user["email"].lower()


def get_user_name(user):
    return user.get("name", "Unknown")
'''

with open("bugfix_demo/app/user_service.py", "w") as f:
    f.write(user_service_code)

print("user_service.py created")

order_service_code = '''
def calculate_discount(amount):
    if amount > 1000:
        return amount * 0.90
    return amount


def calculate_final_price(amount):
    discount = calculate_discount(amount)
    return discount
'''

with open("bugfix_demo/app/order_service.py", "w") as f:
    f.write(order_service_code)

print("order_service.py created")

inventory_code = '''
def get_top_products(products):
    return products[:3]


def calculate_inventory_value(products):
    total = 0

    for product in products:
        total += product["price"] * product["quantity"]

    return total
'''

with open("bugfix_demo/app/inventory.py", "w") as f:
    f.write(inventory_code)

print("inventory.py created")

calculator_tests = '''
import sys
sys.path.append("bugfix_demo/app")

from calculator import calculate_average, calculate_total


def test_average():
    assert calculate_average([10, 20, 30]) == 20


def test_average_empty_list():
    assert calculate_average([]) == 0


def test_total():
    assert calculate_total([10, 20, 30]) == 60
'''

with open("bugfix_demo/tests/test_calculator.py", "w") as f:
    f.write(calculator_tests)

print("test_calculator.py created")

user_tests = '''
import sys
sys.path.append("bugfix_demo/app")

from user_service import get_user_email, get_user_name


def test_email():
    user = {"name": "Kavya", "email": "KAVYA@EXAMPLE.COM"}
    assert get_user_email(user) == "kavya@example.com"


def test_missing_email():
    user = {"name": "Kavya"}
    assert get_user_email(user) == ""


def test_missing_name():
    user = {"email": "kavya@example.com"}
    assert get_user_name(user) == "Unknown"
'''

with open("bugfix_demo/tests/test_users.py", "w") as f:
    f.write(user_tests)

print("test_users.py created")

order_tests = '''
import sys
sys.path.append("bugfix_demo/app")

from order_service import calculate_discount, calculate_final_price


def test_normal_order():
    assert calculate_discount(500) == 500


def test_discount_order():
    assert calculate_discount(1500) == 1350


def test_boundary_order():
    assert calculate_discount(1000) == 900


def test_final_price():
    assert calculate_final_price(1500) == 1350
'''

with open("bugfix_demo/tests/test_orders.py", "w") as f:
    f.write(order_tests)

print("test_orders.py created")

inventory_tests = '''
import sys
sys.path.append("bugfix_demo/app")

from inventory import get_top_products, calculate_inventory_value


def test_top_products():
    products = ["A", "B", "C", "D"]
    assert get_top_products(products) == ["A", "B", "C"]


def test_inventory_value():
    products = [
        {"price": 100, "quantity": 2},
        {"price": 50, "quantity": 4}
    ]

    assert calculate_inventory_value(products) == 400
'''

with open("bugfix_demo/tests/test_inventory.py", "w") as f:
    f.write(inventory_tests)

print("test_inventory.py created")

inventory_tests = '''
import sys
sys.path.append("bugfix_demo/app")

from inventory import get_top_products, calculate_inventory_value


def test_top_products():
    products = ["A", "B", "C", "D"]
    assert get_top_products(products) == ["A", "B", "C"]


def test_inventory_value():
    products = [
        {"price": 100, "quantity": 2},
        {"price": 50, "quantity": 4}
    ]

    assert calculate_inventory_value(products) == 400
'''

with open("bugfix_demo/tests/test_inventory.py", "w") as f:
    f.write(inventory_tests)

print("test_inventory.py created")

import os

for root, dirs, files in os.walk("bugfix_demo"):
    level = root.replace("bugfix_demo", "").count(os.sep)
    indent = "    " * level
    print(indent + os.path.basename(root) + "/")

    for file in files:
        print(indent + "    " + file)

!pytest bugfix_demo/tests -v

!pip install -q -U google-genai langchain langchain-google-genai pytest

import os
from google.colab import userdata

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")

print("Gemini API key loaded:", GEMINI_API_KEY is not None)

from google import genai

client = genai.Client(api_key=GEMINI_API_KEY)

response = client.models.generate_content(
    model="gemini-3.5-flash-lite",
    contents="Explain what a software bug is in one simple sentence."
)

print(response.text)

code = """
def calculate_average(numbers):
    return sum(numbers) / len(numbers)
"""

bug = """
The test test_average_empty_list is failing.

When an empty list is provided, the function throws:
ZeroDivisionError: division by zero.

The expected result for an empty list is 0.
"""

prompt = f"""
You are a software debugging assistant.

Analyze the following Python code and bug report.

CODE:
{code}

BUG REPORT:
{bug}

Give your answer in exactly this structure:

ROOT CAUSE:
Explain why the bug happens.

AFFECTED FUNCTION:
Name the function causing the problem.

PROPOSED FIX:
Explain what should be changed.

CORRECTED CODE:
Provide the corrected Python function.
"""

response = client.models.generate_content(
    model="gemini-3.5-flash-lite",
    contents=prompt
)

print(response.text)

def calculate_average(numbers):
    if len(numbers) == 0:
        return 0
    return sum(numbers) / len(numbers)

from google import genai
from google.colab import userdata

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")

client = genai.Client(api_key=GEMINI_API_KEY)

print("Gemini client ready!")

code = """
def calculate_discount(amount):
    if amount > 1000:
        return amount * 0.90
    return amount
"""

bug = """
The test test_boundary_order is failing.

The business rule says that orders of 1000 or more
should receive a 10 percent discount.

For an order of 1000, the function currently returns 1000,
but the expected result is 900.
"""

prompt = f"""
You are a software debugging assistant.

Analyze the following Python code and bug report.

CODE:
{code}

BUG REPORT:
{bug}

Give your answer in exactly this structure:

ROOT CAUSE:
Explain why the bug happens.

AFFECTED FUNCTION:
Name the function causing the problem.

PROPOSED FIX:
Explain what should be changed.

CORRECTED CODE:
Provide the corrected Python function.
"""

response = client.models.generate_content(
    model="gemini-3.5-flash-lite",
    contents=prompt
)

print(response.text)

import os

def read_repository(repo_path):
    repository = {}

    for root, dirs, files in os.walk(repo_path):

        # Ignore test files for now
        if "tests" in root:
            continue

        for file in files:
            if file.endswith(".py"):
                file_path = os.path.join(root, file)

                with open(file_path, "r") as f:
                    repository[file_path] = f.read()

    return repository


repository = read_repository("bugfix_demo")

print("Files found:")
for file in repository:
    print("-", file)

def create_repository_context(repository):

    context = ""

    for file_path, code in repository.items():

        context += f"""
==============================
FILE: {file_path}
==============================

{code}

"""

    return context


repository_context = create_repository_context(repository)

print(repository_context)

def bug_analyzer(bug_report, repository_context):

    prompt = f"""
You are the Bug Analyzer Agent in an autonomous software debugging system.

You have been given a Python software repository and a bug report.

Your job is to analyze the repository and identify:

1. The affected file
2. The affected function
3. The root cause of the bug
4. Why the current implementation produces the problem
5. What kind of bug it is

Do NOT modify the code.

REPOSITORY:

{repository_context}

BUG REPORT:

{bug_report}

Return your answer using this structure:

AFFECTED FILE:
<file>

AFFECTED FUNCTION:
<function>

BUG TYPE:
<runtime error / logic error / data handling error / other>

ROOT CAUSE:
<explanation>

RECOMMENDED CHANGE:
<what should be changed, without writing the complete code>
"""

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )

    return response.text

bug_report = """
Customers placing an order worth exactly ₹1000
are not receiving the expected 10% discount.

The expected final price for a ₹1000 order is ₹900.
"""

analysis = bug_analyzer(
    bug_report,
    repository_context
)

print(analysis)

def fix_generator(bug_report, repository_context, bug_analysis):

    prompt = f"""
You are the Fix Generator Agent in an autonomous software debugging system.

You have been given:

1. A Python repository
2. A bug report
3. An analysis produced by a Bug Analyzer Agent

Your job is to generate the corrected implementation.

IMPORTANT:
- Fix ONLY the identified bug.
- Do not change unrelated functions.
- Preserve the existing coding style.
- Return the complete corrected function.
- Explain briefly what was changed.

REPOSITORY:
{repository_context}

BUG REPORT:
{bug_report}

BUG ANALYSIS:
{bug_analysis}

Return your answer using exactly this structure:

AFFECTED FILE:
<file path>

AFFECTED FUNCTION:
<function name>

CHANGES MADE:
<short explanation>

CORRECTED CODE:
<complete corrected function>
"""

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )

    return response.text

fix = fix_generator(
    bug_report,
    repository_context,
    analysis
)

print(fix)

import re

def extract_code(ai_response):

    match = re.search(
        r"```python\s*(.*?)```",
        ai_response,
        re.DOTALL
    )

    if match:
        return match.group(1).strip()

    return None


corrected_code = extract_code(fix)

print(corrected_code)

import os

print("Current location:", os.getcwd())
print("\nFiles/folders here:")

for item in os.listdir():
    print("-", item)

print("\nDoes bugfix_demo exist?", os.path.exists("bugfix_demo"))

if os.path.exists("bugfix_demo"):
    for root, dirs, files in os.walk("bugfix_demo"):
        print(root, files)

import os

# Create folders again
os.makedirs("bugfix_demo/app", exist_ok=True)
os.makedirs("bugfix_demo/tests", exist_ok=True)

# Application files
files = {
    "bugfix_demo/app/calculator.py": '''
def calculate_average(numbers):
    return sum(numbers) / len(numbers)


def calculate_total(numbers):
    return sum(numbers)
''',

    "bugfix_demo/app/user_service.py": '''
def get_user_email(user):
    return user["email"].lower()


def get_user_name(user):
    return user.get("name", "Unknown")
''',

    "bugfix_demo/app/order_service.py": '''
def calculate_discount(amount):
    if amount > 1000:
        return amount * 0.90
    return amount


def calculate_final_price(amount):
    discount = calculate_discount(amount)
    return discount
''',

    "bugfix_demo/app/inventory.py": '''
def get_top_products(products):
    return products[:3]


def calculate_inventory_value(products):
    total = 0

    for product in products:
        total += product["price"] * product["quantity"]

    return total
'''
}

# Test files
files.update({
    "bugfix_demo/tests/test_calculator.py": '''
import sys
sys.path.append("bugfix_demo/app")

from calculator import calculate_average, calculate_total


def test_average():
    assert calculate_average([10, 20, 30]) == 20


def test_average_empty_list():
    assert calculate_average([]) == 0


def test_total():
    assert calculate_total([10, 20, 30]) == 60
''',

    "bugfix_demo/tests/test_users.py": '''
import sys
sys.path.append("bugfix_demo/app")

from user_service import get_user_email, get_user_name


def test_email():
    user = {"name": "Kavya", "email": "KAVYA@EXAMPLE.COM"}
    assert get_user_email(user) == "kavya@example.com"


def test_missing_email():
    user = {"name": "Kavya"}
    assert get_user_email(user) == ""


def test_missing_name():
    user = {"email": "kavya@example.com"}
    assert get_user_name(user) == "Unknown"
''',

    "bugfix_demo/tests/test_orders.py": '''
import sys
sys.path.append("bugfix_demo/app")

from order_service import calculate_discount, calculate_final_price


def test_normal_order():
    assert calculate_discount(500) == 500


def test_discount_order():
    assert calculate_discount(1500) == 1350


def test_boundary_order():
    assert calculate_discount(1000) == 900


def test_final_price():
    assert calculate_final_price(1500) == 1350
''',

    "bugfix_demo/tests/test_inventory.py": '''
import sys
sys.path.append("bugfix_demo/app")

from inventory import get_top_products, calculate_inventory_value


def test_top_products():
    products = ["A", "B", "C", "D"]
    assert get_top_products(products) == ["A", "B", "C"]


def test_inventory_value():
    products = [
        {"price": 100, "quantity": 2},
        {"price": 50, "quantity": 4}
    ]

    assert calculate_inventory_value(products) == 400
'''
})

# Write all files
for path, content in files.items():
    with open(path, "w") as f:
        f.write(content)

print("✅ Project recreated successfully!")
print("\nFiles created:")

for path in files:
    print(" -", path)

!pytest bugfix_demo/tests -v

from google import genai
from google.colab import userdata

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")

client = genai.Client(api_key=GEMINI_API_KEY)

print("✅ Gemini client ready!")

import subprocess

def test_fix(file_path, corrected_code):

    # Save the original code
    with open(file_path, "r") as f:
        original_code = f.read()

    try:
        # Temporarily apply AI-generated fix
        with open(file_path, "w") as f:
            f.write(corrected_code)

        print("🔧 AI fix temporarily applied.")
        print("🧪 Running regression tests...\n")

        result = subprocess.run(
            ["pytest", "bugfix_demo/tests", "-v"],
            capture_output=True,
            text=True
        )

        return result

    finally:
        # ALWAYS restore original code
        with open(file_path, "w") as f:
            f.write(original_code)

        print("\n↩️ Original code restored.")

test_result = test_fix(
    "bugfix_demo/app/order_service.py",
    corrected_code
)

print(test_result.stdout)

import re

def apply_function_fix(original_code, corrected_function):

    # Find the original calculate_discount function
    pattern = r"def calculate_discount\(amount\):.*?(?=\n\ndef |\Z)"

    patched_code = re.sub(
        pattern,
        corrected_function.strip(),
        original_code,
        flags=re.DOTALL
    )

    return patched_code

with open("bugfix_demo/app/order_service.py", "r") as f:
    original_order_code = f.read()

patched_order_code = apply_function_fix(
    original_order_code,
    corrected_code
)

print(patched_order_code)

def calculate_discount(amount):
    if amount >= 1000:
        return amount * 0.90
    return amount


def calculate_final_price(amount):
    discount = calculate_discount(amount)
    return discount

import subprocess

def test_fix(file_path, corrected_function):

    # Read original file
    with open(file_path, "r") as f:
        original_code = f.read()

    # Create patched version
    patched_code = apply_function_fix(
        original_code,
        corrected_function
    )

    try:
        # Temporarily apply patched file
        with open(file_path, "w") as f:
            f.write(patched_code)

        print("🔧 Targeted AI fix temporarily applied.")
        print("🧪 Running regression tests...\n")

        result = subprocess.run(
            ["pytest", "bugfix_demo/tests", "-v"],
            capture_output=True,
            text=True
        )

        return result

    finally:
        # Always restore original code
        with open(file_path, "w") as f:
            f.write(original_code)

        print("\n↩️ Original code restored.")

test_result = test_fix(
    "bugfix_demo/app/order_service.py",
    corrected_code
)

print(test_result.stdout)

def reviewer_agent(bug_report, bug_analysis, fix, test_output):

    prompt = f"""
You are the Reviewer Agent in an autonomous software debugging system.

Review the complete debugging process.

BUG REPORT:
{bug_report}

BUG ANALYSIS:
{bug_analysis}

GENERATED FIX:
{fix}

TEST RESULTS:
{test_output}

Determine whether the reported bug was successfully fixed.

IMPORTANT:
- Focus specifically on the reported bug.
- Distinguish the reported bug from unrelated existing test failures.
- Do not claim that all bugs are fixed if unrelated tests still fail.

Return the final report using exactly this structure:

BUG STATUS:
<FIXED / NOT FIXED / NEEDS REVIEW>

AFFECTED FILE:
<file>

AFFECTED FUNCTION:
<function>

ROOT CAUSE:
<short explanation>

FIX APPLIED:
<short explanation>

TARGET TEST:
<PASS / FAIL>

REGRESSION TESTS:
<summary>

FINAL ASSESSMENT:
<2-3 sentence explanation>
"""

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )

    return response.text

review = reviewer_agent(
    bug_report,
    analysis,
    fix,
    test_result.stdout
)

print(review)

def run_bugfix_pipeline(bug_report, target_file, target_function):

    print("=" * 60)
    print("🚀 AUTONOMOUS BUG FIXING PIPELINE")
    print("=" * 60)

    # ------------------------------------------------
    # 1. Read repository
    # ------------------------------------------------
    repository = read_repository("bugfix_demo")
    repository_context = create_repository_context(repository)

    print("\n🔍 STEP 1: BUG ANALYSIS")

    analysis = bug_analyzer(
        bug_report,
        repository_context
    )

    print(analysis)

    # ------------------------------------------------
    # 2. Generate fix
    # ------------------------------------------------
    print("\n🔧 STEP 2: FIX GENERATION")

    fix = fix_generator(
        bug_report,
        repository_context,
        analysis
    )

    print(fix)

    # ------------------------------------------------
    # 3. Extract corrected function
    # ------------------------------------------------
    corrected_function = extract_code(fix)

    if corrected_function is None:
        print("\n❌ Could not extract corrected code.")
        return

    # ------------------------------------------------
    # 4. Test fix
    # ------------------------------------------------
    print("\n🧪 STEP 3: TESTING")

    test_result = test_fix(
        target_file,
        corrected_function
    )

    print(test_result.stdout)

    # ------------------------------------------------
    # 5. Review
    # ------------------------------------------------
    print("\n🔎 STEP 4: REVIEW")

    review = reviewer_agent(
        bug_report,
        analysis,
        fix,
        test_result.stdout
    )

    print(review)

    print("\n" + "=" * 60)
    print("✅ PIPELINE COMPLETE")
    print("=" * 60)

    return {
        "analysis": analysis,
        "fix": fix,
        "test_results": test_result.stdout,
        "review": review
    }

bug_report = """
Customers placing an order worth exactly ₹1000
are not receiving the expected 10% discount.

The expected final price for a ₹1000 order is ₹900.
"""

result = run_bugfix_pipeline(
    bug_report=bug_report,
    target_file="bugfix_demo/app/order_service.py",
    target_function="calculate_discount"
)

bug_report_2 = """
The application crashes when calculate_average()
is called with an empty list.

The expected result for an empty list is 0,
but the application currently throws
ZeroDivisionError.
"""

result_2 = run_bugfix_pipeline(
    bug_report=bug_report_2,
    target_file="bugfix_demo/app/calculator.py",
    target_function="calculate_average"
)

def calculate_average(numbers):
    if len(numbers) == 0:
        return 0
    return sum(numbers) / len(numbers)

bug_report_3 = """
The user profile service crashes when a user
does not have an email address.

A missing email should return an empty string ("")
instead of raising a KeyError.
"""

result_3 = run_bugfix_pipeline(
    bug_report=bug_report_3,
    target_file="bugfix_demo/app/user_service.py",
    target_function="get_user_email"
)

def get_user_email(user):
    return user.get("email", "").lower()

!pip install -q gradio

import gradio as gr

def run_from_ui(bug_report):

    # Decide which module the bug belongs to
    if "average" in bug_report.lower() or "empty list" in bug_report.lower():
        target_file = "bugfix_demo/app/calculator.py"
        target_function = "calculate_average"

    elif "email" in bug_report.lower():
        target_file = "bugfix_demo/app/user_service.py"
        target_function = "get_user_email"

    elif "discount" in bug_report.lower() or "₹1000" in bug_report or "1000" in bug_report:
        target_file = "bugfix_demo/app/order_service.py"
        target_function = "calculate_discount"

    else:
        return (
            "Could not identify the module.",
            "",
            "",
            "Please describe one of the supported bugs."
        )

    result = run_bugfix_pipeline(
        bug_report,
        target_file,
        target_function
    )

    return (
        result["analysis"],
        result["fix"],
        result["test_results"],
        result["review"]
    )

with gr.Blocks(title="AI Bug Fixing Assistant") as demo:

    gr.Markdown(
        """
        # 🤖 AI Bug Fixing Assistant

        Enter a software bug report and let the multi-agent
        system analyze, fix, test and review the bug.
        """
    )

    bug_input = gr.Textbox(
        label="Bug Report",
        placeholder="Example: The application crashes when calculate_average() receives an empty list...",
        lines=5
    )

    analyze_button = gr.Button("🔍 Analyze & Fix")

    gr.Markdown("## 🔍 Bug Analysis")
    analysis_output = gr.Textbox(lines=8)

    gr.Markdown("## 🔧 Generated Fix")
    fix_output = gr.Textbox(lines=10)

    gr.Markdown("## 🧪 Test Results")
    test_output = gr.Textbox(lines=12)

    gr.Markdown("## 🔎 Final Review")
    review_output = gr.Textbox(lines=10)

    analyze_button.click(
        fn=run_from_ui,
        inputs=bug_input,
        outputs=[
            analysis_output,
            fix_output,
            test_output,
            review_output
        ]
    )

demo.launch(share=True)

def get_baseline_tests():
    result = subprocess.run(
        ["pytest", "bugfix_demo/tests", "-q"],
        capture_output=True,
        text=True
    )
    return result.stdout


baseline = get_baseline_tests()

print("BASELINE TEST RESULTS:")
print(baseline)

def run_from_ui(bug_report):

    if "average" in bug_report.lower() or "empty list" in bug_report.lower():
        target_file = "bugfix_demo/app/calculator.py"
        target_function = "calculate_average"

    elif "email" in bug_report.lower():
        target_file = "bugfix_demo/app/user_service.py"
        target_function = "get_user_email"

    elif "discount" in bug_report.lower() or "₹1000" in bug_report or "1000" in bug_report:
        target_file = "bugfix_demo/app/order_service.py"
        target_function = "calculate_discount"

    else:
        return (
            "❌ Bug type could not be identified.",
            "",
            "",
            "Please enter a bug related to average calculation, discount calculation, or missing email."
        )

    result = run_bugfix_pipeline(
        bug_report,
        target_file,
        target_function
    )

    return (
        result["analysis"],
        result["fix"],
        result["test_results"],
        result["review"]
    )

def reviewer_agent(
    bug_report,
    bug_analysis,
    fix,
    test_output,
    target_file,
    target_function
):

    prompt = f"""
You are the Reviewer Agent in an autonomous software debugging system.

Review the complete debugging process.

BUG REPORT:
{bug_report}

ACTUAL AFFECTED FILE:
{target_file}

ACTUAL AFFECTED FUNCTION:
{target_function}

BUG ANALYSIS:
{bug_analysis}

GENERATED FIX:
{fix}

TEST RESULTS:
{test_output}

Determine whether the reported bug was successfully fixed.

IMPORTANT:
- Use the ACTUAL AFFECTED FILE and FUNCTION provided above.
- Do not invent a different file name.
- Focus specifically on the reported bug.
- Distinguish the reported bug from unrelated existing test failures.

Return:

BUG STATUS:
<FIXED / NOT FIXED / NEEDS REVIEW>

AFFECTED FILE:
{target_file}

AFFECTED FUNCTION:
{target_function}

ROOT CAUSE:
<short explanation>

FIX APPLIED:
<short explanation>

TARGET TEST:
<PASS / FAIL>

REGRESSION TESTS:
<summary>

FINAL ASSESSMENT:
<2-3 sentences>
"""

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )

    return response.text

review = reviewer_agent(
    bug_report,
    analysis,
    fix,
    test_result.stdout,
    "bugfix_demo/app/order_service.py",
    "calculate_discount"
)

print(review)

def run_bugfix_pipeline(bug_report, target_file, target_function):

    print("=" * 60)
    print("🚀 AUTONOMOUS BUG FIXING PIPELINE")
    print("=" * 60)

    # 1. Read repository
    repository = read_repository("bugfix_demo")
    repository_context = create_repository_context(repository)

    print("\n🔍 STEP 1: BUG ANALYSIS")

    analysis = bug_analyzer(
        bug_report,
        repository_context
    )

    print(analysis)

    # 2. Generate fix
    print("\n🔧 STEP 2: FIX GENERATION")

    fix = fix_generator(
        bug_report,
        repository_context,
        analysis
    )

    print(fix)

    # 3. Extract corrected function
    corrected_function = extract_code(fix)

    if corrected_function is None:
        print("\n❌ Could not extract corrected code.")

        return {
            "analysis": analysis,
            "fix": fix,
            "test_results": "Fix could not be extracted.",
            "review": "NEEDS REVIEW"
        }

    # 4. Test fix
    print("\n🧪 STEP 3: TESTING")

    test_result = test_fix(
        target_file,
        corrected_function
    )

    print(test_result.stdout)

    # 5. Reviewer
    print("\n🔎 STEP 4: REVIEW")

    review = reviewer_agent(
        bug_report,
        analysis,
        fix,
        test_result.stdout,
        target_file,
        target_function
    )

    print(review)

    print("\n" + "=" * 60)
    print("✅ PIPELINE COMPLETE")
    print("=" * 60)

    return {
        "analysis": analysis,
        "fix": fix,
        "test_results": test_result.stdout,
        "review": review
    }

bug_report = """
Customers placing an order worth exactly ₹1000
are not receiving the expected 10% discount.

The expected final price for a ₹1000 order is ₹900.
"""

result = run_bugfix_pipeline(
    bug_report,
    "bugfix_demo/app/order_service.py",
    "calculate_discount"
)

bug_report = """
Customers placing an order worth exactly ₹1000
are not receiving the expected 10% discount.

The expected final price for a ₹1000 order is ₹900.
"""

result = run_bugfix_pipeline(
    bug_report,
    "bugfix_demo/app/order_service.py",
    "calculate_discount"
)

import gradio as gr

def run_from_ui(bug_report):

    if not bug_report.strip():
        return (
            "Please enter a bug report.",
            "",
            "",
            ""
        )

    # Identify target module
    if "average" in bug_report.lower() or "empty list" in bug_report.lower():
        target_file = "bugfix_demo/app/calculator.py"
        target_function = "calculate_average"

    elif "email" in bug_report.lower():
        target_file = "bugfix_demo/app/user_service.py"
        target_function = "get_user_email"

    elif "discount" in bug_report.lower() or "₹1000" in bug_report or "1000" in bug_report:
        target_file = "bugfix_demo/app/order_service.py"
        target_function = "calculate_discount"

    else:
        return (
            "❌ Could not identify the bug type.",
            "",
            "",
            "Please describe an average, discount, or missing-email bug."
        )

    # Run complete pipeline
    result = run_bugfix_pipeline(
        bug_report,
        target_file,
        target_function
    )

    return (
        result["analysis"],
        result["fix"],
        result["test_results"],
        result["review"]
    )


with gr.Blocks(title="AI Bug Fixing Assistant") as demo:

    gr.Markdown("""
    # 🤖 AI Bug Fixing Assistant

    Enter a software bug report and the multi-agent system will
    analyze, fix, test and review the bug.
    """)

    bug_input = gr.Textbox(
        label="Bug Report",
        placeholder="Describe the software bug here...",
        lines=5
    )

    analyze_button = gr.Button("🔍 Analyze & Fix")

    analysis_output = gr.Textbox(
        label="🔍 Bug Analysis",
        lines=8
    )

    fix_output = gr.Textbox(
        label="🔧 Generated Fix",
        lines=10
    )

    test_output = gr.Textbox(
        label="🧪 Test Results",
        lines=12
    )

    review_output = gr.Textbox(
        label="🔎 Final Review",
        lines=10
    )

    analyze_button.click(
        fn=run_from_ui,
        inputs=bug_input,
        outputs=[
            analysis_output,
            fix_output,
            test_output,
            review_output
        ]
    )

demo.launch(share=True)

def generate_patch_summary(
    bug_report,
    target_file,
    target_function,
    analysis,
    fix,
    test_output
):

    prompt = f"""
Create a concise software change summary for the following bug fix.

BUG REPORT:
{bug_report}

FILE:
{target_file}

FUNCTION:
{target_function}

ROOT CAUSE:
{analysis}

GENERATED FIX:
{fix}

TEST RESULTS:
{test_output}

Return exactly this format:

CHANGE SUMMARY

File:
<file>

Function:
<function>

Problem:
<one sentence>

Change Made:
<one sentence describing the code change>

Why:
<one sentence explaining why>

Validation:
<short test result>

Status:
<FIXED / NOT FIXED / NEEDS REVIEW>
"""

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )

    return response.text

patch_summary = generate_patch_summary(
    bug_report,
    "bugfix_demo/app/order_service.py",
    "calculate_discount",
    result["analysis"],
    result["fix"],
    result["test_results"]
)

print(patch_summary)

